runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  # Add environment variables here as needed
  EXAMPLE_VAR: example_value

# Automatic scaling settings
automatic_scaling:
  min_instances: 1
  max_instances: 10
  cool_down_period: 120s
  cpu_utilization:
    target_utilization: 0.6

# Resources (CPU, memory) allocation
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Health check settings
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
